site_name: EMR and LIS Data Exchange Knowledge Base
nav:
    - Home: index.md
    - About: about.md
    - HIE Workflows: hie-workflows.md
    - FAQ: faq.md
    - Get Additional Help: get-additional-help.md
theme: readthedocs
