site_name: EMR and LIS Data Exchange Knowledge Base
site_url: ""
use_directory_urls: false
nav:
  - Introduction: "index.md"
  - Demo Servers: "demo-directory.md"
  - Laboratory Workflows: lis-workflows/lis-workflows.md
  - Client Registry / MPI Workflows: mpi-workflows.md
  - FAQ: faq.md
  - About: "about.md"
  - Get Additional Help: get-additional-help.md
theme: readthedocs
extra_css:
  - css/extra.css
plugins:
  - search
  - include-markdown
  - build_plantuml:
        render: "server"
        bin_path: "/usr/local/bin/plantuml" # ignored when render: server
        server: "http://www.plantuml.com/plantuml" # offical plantuml server
        disable_ssl_certificate_validation: true # for self-signed and invalid certs
        output_format: "png" # or "png"
        diagram_root: "docs/diagrams" # should reside under docs_dir
        output_folder: "out"
        input_folder: "src"
        input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
